
@jwt =


### Poducts Index

GET http://localhost:3000/products.json?category=books

POST http://localhost:3000/one_product
Content-Type: application/json


{   "name" :"mystery box", "description" :"It's a mystery","price" : 15, "image_url" : "mysterybox.edu"}

###
GET http://localhost:3000/product
Content-Type: application/json
### products show
PATCH http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer {{@jwt}}

{ 
  "name": "New Box",
  "description" : "Not the last box, a new box",
  "price": 16,
  "image_url": "image1.com"
}

DELETE http://localhost:3000/product/1
Content-Type: application/json


### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Photos create
POST http://localhost:3000/photos.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyIjozLCJleHAiOjE2Mjk5OTI4NjR9.G2ExsrDYn3oE0vJkvm4T6Po2GbNpH5cqTEaVPVuK_MA
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}

### orders create
POST http://localhost:3000/orders.json
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ "user_id": 3, "product_id": 3, "quantity": 3, "subtotal": 40, 
"tax": 5, 
"total":45
  
}
  
### ORDERS SHOW

GET http://locatlhost:3000/orders/1.json
Authorization: Bearer {}


### ORDERS Index

GET http://locatlhost:3000/orders



GET http://localhost:3000/product
Content-Type: application/json

### CARTED PRODUCTS
GET http://localhost:3000/carted_product.json
Authorization: Bearer {{jwt}}

### CARTED_PRODUCT CREATE
POST http://localhost:3000/carted_products
Content-Type: application/json
Authorization: Bearer {{jwt}}

{ "product_id": 3, "quantity": 3 
  
}
### CARTED PRODUCTS DELETE
DELETE http://localhost:3000/carted_product/2

Authorization: Bearer {{jwt}}
