POST http://localhost:3000/one_product
Content-Type: application/json


{   "name" :"mystery box", "description" :"It's a mystery","price" : 15, "image_url" : "mysterybox.edu"}

###
GET http://localhost:3000/product
Content-Type: application/json
###
PATCH http://localhost:3000/product
Content-Type: application/json


{ 
  "name": "New Box",
  "description" : "Not the last box, a new box",
  "price": 16,
  "image_url": "image1.com"
}